// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFC0vbyslqR-BHfZGquVGwhBWe_qj6ya4',
    appId: '1:438105416933:web:f4dfdbb00e48e7512ea00c',
    messagingSenderId: '438105416933',
    projectId: 'ecommerce-edc45',
    authDomain: 'ecommerce-edc45.firebaseapp.com',
    storageBucket: 'ecommerce-edc45.appspot.com',
    measurementId: 'G-NGQBTQC8DM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCushLMtLwx-YPfCHM8z5M9h-bELyelWW0',
    appId: '1:438105416933:android:e923dc0027911b592ea00c',
    messagingSenderId: '438105416933',
    projectId: 'ecommerce-edc45',
    storageBucket: 'ecommerce-edc45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-w8s7RRb6MrlD68NfKPHlNh486LNZQ10',
    appId: '1:438105416933:ios:96d0f97c12c4b9db2ea00c',
    messagingSenderId: '438105416933',
    projectId: 'ecommerce-edc45',
    storageBucket: 'ecommerce-edc45.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );
}
